### ISSUE TITLE
Are there any layers available for non-idegninours species, ticks, fish

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#175]

**Comment by sasignell** [comment]
I assume they're talking about invasive animals (we already have plants)

Can't we just replicate the invasive plants layer, but for animals?

**Comment by caryfitzhugh** [comment]
I believe we could do the same sort of thign for invaisve animals...  I
could modify the scraper and pull in invaisive animals.  ANd make a
separate layer.

**Comment by caryfitzhugh** [comment]
@colinbeier I think we can pull in a few from imapinvasives?

![image](https://cloud.githubusercontent.com/assets/445848/13968014/9292eeb4-f050-11e5-9471-3fbeae8b67c0.png)

I have no idea what else we could / should use. But those 5 species don't seem that interesting (to me at least).

I googled and saw this - but don't know if it is good.  Seems like a focus on water-things, and only a few bigger animals.    The API is some sort of kml / xml thing, not sure if we can get it.

http://nas.er.usgs.gov/queries/SpeciesList.aspx?group=&state=NY&Sortby=1
http://nas.er.usgs.gov/viewer/omap.aspx?SpeciesID=2244

This place has some data too... 
https://www.eddmaps.org/distribution/

Not sure if we can get it.

Easy answer is no. There isn't much else.

**Comment by colinbeier** [comment]
I thought the rare plants and animals later has a non-native category?

Colin Beier
SUNY ESF

On Mar 22, 2016 5:14 PM, Cary FitzHugh <notifications@github.com> wrote:

@colinbeier<https://github.com/colinbeier> I think we can pull in a few from imapinvasives?

[image]<https://cloud.githubusercontent.com/assets/445848/13968014/9292eeb4-f050-11e5-9471-3fbeae8b67c0.png>

I have no idea what else we could / should use. But those 5 species don't seem that interesting (to me at least).

I googled and saw this - but don't know if it is good. Seems like a focus on water-things, and only a few bigger animals. The API is some sort of kml / xml thing, not sure if we can get it.

http://nas.er.usgs.gov/queries/SpeciesList.aspx?group=&state=NY&Sortby=1
http://nas.er.usgs.gov/viewer/omap.aspx?SpeciesID=2244

This place has some data too...
https://www.eddmaps.org/distribution/

Not sure if we can get it.

Easy answer is no. There isn't much else.

**Comment by caryfitzhugh** [comment]
![image](https://cloud.githubusercontent.com/assets/445848/13968675/6e8ac308-f054-11e5-8146-4a5ab727ef64.png)

I see there are 5 insects. (or so... )

I don't know what you mean about non-native.  iMapInvasives is all I have... ?

**Comment by colinbeier** [comment]
Several of these are pretty important invasives in aquatic systems: Asian Clam, Common Carp, Quagga Mussel, Round Goby, Zebra Mussel.  We could include all five of those.  

These insects would also be good to include.  Eh, we could leave out the Stink Bug.  The other three (Emerald Ash Borer, Asian Long-Horned Beetle, Hemlock Wooly Adelgid) are major forest pests.  

This should be enough satisfy their request.  Ticks are not invasive, but the Lyme disease problem is likely what they are after, but I would argue that's not climate-relevant enough.  By adding these other species, we might want to reorganize the invasive species layer.  Easiest thing to do will be to create a subfolder in Ecosystems named 'Invasive Species', move Invasive Plant Species there and create two new layers called 'Invasive Aquatic Fish & Bivalves' and 'Forest Insect Pests' with the species that are listed above.  

Ecosystems >
	Invasive Species >
		Invasive Plants (toggle among species, with all species)
		Invasive Fish & Bivalves (toggle among species, with all species) 
		Forest Insect Pests (toggle among species, with all species) 

Let me know if any of this is unclear.  Thanks!

**Comment by sasignell** [comment]
Hey I was working on creating an animals version of the invasive plants layer when I realized the invasives layer is pulling from a static file that Cary scraped a while back (see #120).  Cary-- do you still have the code you used to scrape this?  I can set up cron tasks to bring in versions for plants, animals and insects then and have a layer for each.

**Comment by caryfitzhugh** [comment]
Yes, in the server/scripts/invasives.js file it does the scraping.

Once I get the animals / insects scraped as well, I can tell you what cron
job to run... That work?

**Comment by sasignell** [comment]
sounds like a plan.  Let me know if you want me to create the insect &
animal layers once we've done that.

On Wed, Mar 23, 2016 at 8:24 AM, Cary FitzHugh <notifications@github.com>
wrote:

> Yes, in the server/scripts/invasives.js file it does the scraping.
>
> Once I get the animals / insects scraped as well, I can tell you what cron
> job to run... That work?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/175#issuecomment-200326960>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
@sasignell ok. I've created two new scripts, and renamed one.

invasive_plants.js
invasive_animals.js
invasive_insects.js

All three need to be run like so in the cron:

./invasive_plants.js > invasive_plants.json


The resulting .json files need to be put into the www/data directory so they can be requested by the web-map.

I have put the three files on the geoserver, and checked them into the repository.
I have renamed "invasives" to "invasive_plants"
You can add the two other layers, and move them to the new folder.

Sound good?

**Comment by colinbeier** [comment]
Somethin buggy going on when I try to turn these layers on... not sure if they are ready for primetime yet, so sorry if I'm twiddling prematurely (insert crass joke here)

**Comment by caryfitzhugh** [comment]
Right. not completed just yet :)

**Comment by sasignell** [comment]
I'll get to this tonight

**Comment by sasignell** [comment]
I installed some node modules but getting this error when I try to run the
pant script:

TypeError: Object #<Object> has no method 'forEachOf'
    at Object.<anonymous>
(/var/www/html/NYCCSC-map-viewer/server/scripts/invasives/invasive_plants.js:60:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3


On Wed, Mar 23, 2016 at 8:15 PM, Steve Signell <steve@frontierspatial.com>
wrote:

> I'll get to this tonight
> On Mar 23, 2016 7:35 PM, "Cary FitzHugh" <notifications@github.com> wrote:
>
>> Right. not completed just yet :)
>>
>> On Wed, Mar 23, 2016 at 5:42 PM, colinbeier <notifications@github.com>
>> wrote:
>>
>> > Somethin buggy going on when I try to turn these layers on... not sure
>> if
>> > they are ready for primetime yet, so sorry if I'm twiddling prematurely
>> > (insert crass joke here)
>> >
>> > On Mar 23, 2016, at 3:19 PM, Cary FitzHugh wrote:
>> >
>> > > @sasignell ok. I've created two new scripts, and renamed one.
>> > >
>> > > invasive_plants.js
>> > > invasive_animals.js
>> > > invasive_insects.js
>> > >
>> > > All three need to be run like so in the cron:
>> > >
>> > > ./invasive_plants.js > invasive_plants.json
>> > >
>> > > The resulting .json files need to be put into the www/data directory
>> so
>> > they can be requested by the web-map.
>> > >
>> > > I have put the three files on the geoserver, and checked them into the
>> > repository.
>> > > I have renamed "invasives" to "invasive_plants"
>> > > You can add the two other layers, and move them to the new folder.
>> > >
>> > > Sound good?
>> > >
>> > > —
>> > > You are receiving this because you were mentioned.
>> > > Reply to this email directly or view it on GitHub
>> > >
>> >
>> > —
>> > You are receiving this because you commented.
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/175#issuecomment-200554669
>> >
>> >
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/175#issuecomment-200583045>
>>
>


-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
ack... hrm....

Let me look at this today... hrm...

**Comment by caryfitzhugh** [comment]
@sasignell what version of node are you running?

**Comment by caryfitzhugh** [comment]
I updated the package.json. so npm install should give you what you need now...
sorry about that!

**Comment by sasignell** [comment]
Cool I'll try it out this afternoon

**Comment by colinbeier** [comment]
What's the status on this one? It is still buggy on the gh page

**Comment by caryfitzhugh** [comment]
putting the last touches on it now.
