### ISSUE TITLE
cloning gone?  

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#200]
Cary, was just monkeying around on the gh page of the CCSC map, and noticed that all of the clone icons / buttons are gone.  Any notion whats up here?

**Comment by caryfitzhugh** [comment]
Oy... no!  I am still in Boston, but can look...  oy oy... no idea off the
top of my head.

**Comment by caryfitzhugh** [comment]
This is on gh-pages... Duh. some weird JS issue... 

I could release next week...

**Comment by colinbeier** [comment]
sorry.. the issue is only on gh-pages, or you fixed it on gh-pages and we need a new release so it works in the production site, or... ?

**Comment by caryfitzhugh** [comment]
I pushed my fixes to gh-pages. I saw the issue immediately.
We need a release to get it to Cornell.

**Comment by colinbeier** [comment]
OK, well we're still in a holding pattern on releasing / launching the site, now a week later than expected.  So might as well release ASAP to fix the bug.  I still don't have new slides because, well, end of semester craziness will be my excuse.  But we should fix the bug...

**Comment by caryfitzhugh** [comment]
Fixed I believe.
